/*
 * Ultrasonic_Config.h
 *
 *  Created on: Oct 27, 2022
 *      Author: TECH VALLEY
 */

#ifndef HAL_ULTRASONIC_ULTRASONIC_CONFIG_H_
#define HAL_ULTRASONIC_ULTRASONIC_CONFIG_H_


#define ULTRASONIC_TRIGGER_PIN    PC5_PIN

#endif /* HAL_ULTRASONIC_ULTRASONIC_CONFIG_H_ */
